Scale Stack fix
jhuapl-boss/boss-manage pull request #108
Opened 2021-09-30 19:55 UTC by dxenes1

Fixes issue in the scale stack utility where endpoint would start before vault or bastion and cause issues. Enforces order of operations and waits for instances to start before starting the next dependent.

2021-09-30 20:04 UTC, movestill requested changes
Nice, let's just switch to using the provided wait functions. You can configure the delay to be less than 15s. Maybe 5s is a good value?

2021-09-30 20:04 UTC, movestill commented on bin/scale_stack.py
> +def wait_for_instance(ec2_client, instance_name):
boto3 has a waiter for this: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Waiter.InstanceRunning

2021-10-15 23:01 UTC, movestill commented on bin/scale_stack.py
> +            'Values': ['pending', 'running', 'stopped']
Ah, I was thinking they were exclusive.

2021-10-15 23:01 UTC, movestill approved these changes

2021-11-01 15:42 UTC, sandyhider approved these changes

2021-11-01 15:42 UTC, merged